steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/find-your-nest', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/find-your-nest']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'find-your-nest', '--image', 'gcr.io/$PROJECT_ID/find-your-nest', '--region', 'europe-west','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/find-your-nest

