# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTestcreercompte():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_creercompte(self):
    self.driver.get("https://find-your-nest-ywhzbcfbpq-ew.a.run.app/")
    self.driver.set_window_size(814, 853)
    self.driver.find_element(By.LINK_TEXT, "Se connecter").click()
    self.driver.find_element(By.LINK_TEXT, "Pas encore inscrit(e)?").click()
    self.driver.find_element(By.ID, "exampleInputName").click()
    self.driver.find_element(By.ID, "exampleInputName").send_keys("test_selenium")
    self.driver.find_element(By.ID, "exampleInputMail").click()
    self.driver.find_element(By.ID, "exampleInputMail").send_keys("testselenium@hotmail.fr")
    self.driver.find_element(By.ID, "exampleInputPassword").click()
    self.driver.find_element(By.ID, "exampleInputPassword").send_keys("test")
    self.driver.find_element(By.NAME, "confirmer").click()
    self.driver.find_element(By.NAME, "confirmer").send_keys("test")
    self.driver.find_element(By.ID, "exampleInputNumber").click()
    self.driver.find_element(By.ID, "exampleInputNumber").send_keys("6")
    self.driver.find_element(By.ID, "exampleInputStreet").click()
    self.driver.find_element(By.ID, "exampleInputStreet").send_keys("rue rougemont")
    self.driver.find_element(By.ID, "exampleInputCity").click()
    self.driver.find_element(By.ID, "exampleInputCity").send_keys("Paris")
    self.driver.find_element(By.ID, "exampleInputZip").click()
    self.driver.find_element(By.ID, "exampleInputZip").send_keys("75009")
    self.driver.find_element(By.ID, "Time").click()
    self.driver.find_element(By.ID, "Time").send_keys("00:04")
    self.driver.find_element(By.ID, "Time").send_keys("00:45")
    element = self.driver.find_element(By.ID, "priceRange")
    actions = ActionChains(driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "priceRange")
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "priceRange")
    actions = ActionChains(driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "priceRange").send_keys("950")
    self.driver.find_element(By.ID, "priceRange").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-check:nth-child(2) > .form-check-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
  
