# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTestlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://find-your-nest-ywhzbcfbpq-ew.a.run.app/")
    self.driver.set_window_size(814, 853)
    self.driver.find_element(By.LINK_TEXT, "Se connecter").click()
    self.driver.find_element(By.ID, "exampleInputMail").click()
    self.driver.find_element(By.ID, "exampleInputMail").send_keys("testselenium@hotmail.fr")
    self.driver.find_element(By.ID, "exampleInputPassword").click()
    self.driver.find_element(By.ID, "exampleInputPassword").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".float-right").click()
  
