# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTestafficherlogement():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testafficherlogement(self):
    self.driver.get("https://find-your-nest-ywhzbcfbpq-ew.a.run.app/")
    self.driver.set_window_size(814, 853)
    self.driver.find_element(By.ID, "exampleInputAddress").click()
    self.driver.find_element(By.ID, "ui-id-15").click()
    self.driver.find_element(By.ID, "exampleInputAddress").send_keys("6 Rue Rougemont 75009 Paris")
    self.driver.find_element(By.ID, "exampleInputHour").click()
    self.driver.find_element(By.ID, "exampleInputHour").send_keys("0")
    self.driver.find_element(By.ID, "exampleInputMin").send_keys("15")
    self.driver.find_element(By.ID, "btn-1").click()
    self.driver.find_element(By.LINK_TEXT, "+ d\'infos").click()
  
