# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(814, 860)
    self.driver.find_element(By.ID, "exampleInputAddress").click()
    self.driver.find_element(By.ID, "ui-id-11").click()
    self.driver.find_element(By.ID, "exampleInputAddress").send_keys("2 Rue des Clos Moreaux 92190 Meudon")
    self.driver.find_element(By.ID, "exampleInputHour").click()
    self.driver.find_element(By.ID, "exampleInputHour").send_keys("1")
    self.driver.find_element(By.ID, "exampleInputMin").click()
    self.driver.find_element(By.ID, "exampleInputMin").send_keys("1")
    self.driver.find_element(By.ID, "btn-1").click()
  

